config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'
  get 'greeter/hello' => "greeter#hello" # greeter - controller , hello - action
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'greeter/goodbye'

  root 'courses#index' #what if we wanted the root path go to the index action?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coursera.rb
class Coursera
    include HTTParty

    base_uri 'https://api.coursera.org/api/catalog.v1/courses' # API DO SITE
    default_params fields: "smallIcon, shortDescription", q: "search"
    format :json

    def self.for term 
        get("" , query: { query: term})["elements"]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @search_term = params[:looking_for] || 'jhu'
    @courses = Coursera.for(@search_term)
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    random_names = ["Alex" , "Joe" , "Michael"]
    @name = random_names.sample
    @time = Time.now
    @times_displayed ||= 0
    @times_displayed += 1
  end
  def goodbye # A seguir acrescentar nos routes get 'greeter/goodbye'
  end
end

# Controller contains actions ( methods )

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
    def formatted_time (time)
        time.strftime("%I:%M:%p")
    end
end

app/views/courses/index.html.erb
<h1>Courses#index</h1>
<p>Find me in app/views/courses/index.html.erb</p>

<h1> Searching for - <%= @search_term %>

<table border = "1">
    <tr>
        <th> Image </th>
        <th> Name </th>
        <th> Description </th>
    </tr>

    <% @courses.each do |course| %>
        <!-- root path-->
        <tr class=<%= cycle('even' , 'odd' ) %>>
            <td><%= image_tag(course["smallIcon"])%></td>
            <td><%= course["name"] %></td>
            <td><%= course["shortDescription"] %></td>
        </tr>

    <% end %>    
</table>

app/views/greeter/goodbye.html.erb
<h1> GoodBye <h1>

app/views/greeter/hello.html.erb
<h1> Greetings, <%= @name %>
<!--<p>Find me in app/views/greeter/hello.html.erb</p>
<p> Time now is : <%= @time %>-->
<p> The time now is <%= formatted_time(@time)%>
<p> This page has been viewed <%= @times_displayed %> time(s) </p>

<!-- Vai sempre aparecer 1 porque sempre vai recomeçar do 0 -->

<p><%= link_to "Google", "http://google.pt/" %> </p>
<p> <%= link_to "Goodbye", greeter_goodbye_path %>

app/views/layouts/application.html.erb
<!-- View Container -->

<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Introdução de mais uma linha csrf-->
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>